pipeline {
  agent {
    node 'mac-1'
  } 
  stages {
      stage(‘Sample’) {
          when {
            environment ignoreCase: true, name: 'MY_ENV_VAR', value: 'doit'
            beforeAgent true
          }
        steps {
            sh 'touch /Users/jenkins/IFISEETHISFILETHESTEPRAN'
          }
      }
  }
}
